#!/usr/bin/perl

# $Id: adj2sif 597 2010-06-23 01:06:56Z zola $
#
# File: adj2sif
# Developed: Feb 21, 2009
#
# Author: Jaroslaw Zola <jaroslaw.zola@gmail.com>
#
# Copyright 2007-2010 Jaroslaw Zola
#
# This file is part of TINGe.
#
# TINGe is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# TINGe is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with TINGe. If not, see <http://www.gnu.org/licenses/>.

use strict;
use warnings;


my $usage = "usage: adj2sif infile\n";
die $usage if (@ARGV != 1);

my $infile = $ARGV[0];
my $sif_file = "";
my $eda_file = "";

($sif_file = $infile) =~ s/\.c?adj$//;
$eda_file = $sif_file . ".weight.eda";
$sif_file .= ".sif";

open(INPUT, "< $infile") or die "error: can't open input file\n";
open(OUTPUT_SIF, "> $sif_file") or die "error: can't open sif file\n";
open(OUTPUT_EDA, "> $eda_file") or die "error: can't open eda file\n";

print OUTPUT_EDA "Weight\n";

# adj reading integrated for efficiency

# skip comments
my $input;
while ((defined ($input = <INPUT>)) && ($input =~ m/^>/)) { }

if (defined $input) {
    # process data
    do {
	chomp($input);

	my @line = split("\t", $input);
	my $len = scalar(@line);
	die "error: data corrupted\n" if (($len < 3) || (($len - 1) % 2 != 0));

	my $s = $line[0];
	for (my $i = 1; $i < $len; $i += 2) {
	    my $t = $line[$i];
	    my $edge = "$s pp $t";
	    $edge = "$t pp $s" if ($t lt $s);
	    print OUTPUT_SIF "$edge\n";
	    $edge =~ s/pp/(pp)/;
	    print OUTPUT_EDA "$edge = $line[$i + 1]\n";
	}
    } while ($input = <INPUT>);
}

close(OUTPUT_EDA);
close(OUTPUT_SIF);
close(INPUT);
