#!/usr/bin/perl

# $Id: exp-size 597 2010-06-23 01:06:56Z zola $
#
# File: exp-size
# Developed: Mar 02, 2009
#
# Author: Jaroslaw Zola <jaroslaw.zola@gmail.com>
#
# Copyright 2007-2010 Jaroslaw Zola
#
# This file is part of TINGe.
#
# TINGe is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# TINGe is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with TINGe. If not, see <http://www.gnu.org/licenses/>.

use strict;
use warnings;


my $usage = "usage: exp-size infile\n";
die $usage if (@ARGV != 1);

my $nrow = 0;
my $ncol = 0;
my $pval = "";

open(INPUT, "< $ARGV[0]") or die "error: can't open input file\n";

my $head = <INPUT>;
if (defined $head) {
    chomp($head);

    my @line = split("\t", $head);
    $ncol = scalar(@line) - 2;

    my $tmp;
    while (<INPUT>) {
	next if (lc($_) =~ m/^description/);
	$nrow++;
	$tmp = $_;
    }

    if (defined $tmp) {
	@line = split("\t", $tmp);
	$pval = " p-vals" if ((2 * $ncol) == (@line - 2));
    }
}

close(INPUT);

print "$nrow $ncol$pval\n";
